language: java
dist: bionic
jdk: openjdk11

jobs:
  allow_failures:
    - stage: test
  include:
    - stage: build
      script:
        - mvn clean install -B -V -DskipTests
        - mvn javadoc:javadoc
        - .util/pages.sh
    - stage: test
      script:
        - mvn clean install -B -V
